# The URL the site will be built for
base_url = "https://bobakmariusz.github.io"

title = "Mariusz Bobak - Blog"
description = "Blog na temat technologii - w sczególności o architekturze, sieciach neuronowych oraz wszechobecnej sztucznej inteligencji"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Build output directory
output_dir = "docs"

# Template
theme = "radion"

# RSS

generate_feeds = true

# Language
default_language = "pl" 


taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

# Search
#build_search_index = true

[search]
#index_format = "elasticlunr_json"

# Additional
minify_html = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "one-dark"

[extra]
# Put all your custom variables here
theme = "toggle"
toc = true
#enable_search = true
codeblock = true
latex = true

author = "Mariusz Sebastian Bobak - Zawałowczyn"

# Comments
comments = true
giscus_repo = "bobakmariusz/bobakmariusz.github.io"
giscus_repo_id = "R_kgDOOM3PUA"
giscus_data_category_id = "DIC_kwDOOM3PUM4CoW01"


github = "https://github.com/BobakMariusz"

# menau
radion_menu = [
    {url = "$BASE_URL", name = "Strona główna"},
    {url = "$BASE_URL/categories", name = "Kategorie"},
    {url = "$BASE_URL/tags", name = "Tagi"},
]
